### ISSUE TITLE
Change module path from `oxia` to `github.com/streamnative/oxia`

### ISSUE THREAD

**Issue by lsytj0413** [streamnative/oxia#380]
current module path `oxia` is too short, and base on [golang's suggest](https://go.dev/ref/mod):

```
A module path should describe both what the module does and where to find it. Typically, a module path consists of a repository root path, a directory within the repository (usually empty), and a major version suffix (only for major version 2 or higher).
```

and [other's golang module](https://github.com/streamnative/function-mesh/blob/master/go.mod) also formatted as `github.com/streamnative/xxx`, so should we change this module path to `github.com/streamnative/oxia`？

**Comment by mattisonchao** [comment]
@merlimat what is your opinion by any chance?

**Comment by merlimat** [comment]
Yes, it does make sense to change. I think we used the short module name because the repo was originally private and made things a bit more difficult.

**Comment by lsytj0413** [comment]
@mattisonchao  Could i make this change？
