### ISSUE TITLE
【Feature】add crc to wal

### ISSUE THREAD

**Issue by lsytj0413** [streamnative/oxia#407]
oxia use wal to storage the `LogEntry` in segment files, should we add `crc` to each record to protect data corrupted？

**Comment by merlimat** [comment]
Yes, one idea was to use a crc based on the past entries of the log as well. (eg: similar to git history). That would help in identifying any issues in non-common histories of the wal across nodes.

**Comment by merlimat** [comment]
@lsytj0413 Perhaps we can start with a proposal and design doc for how to implement the change. We can use discussions. eg: https://github.com/streamnative/oxia/discussions/new?category=proposal

**Comment by lsytj0413** [comment]
> @lsytj0413 Perhaps we can start with a proposal and design doc for how to implement the change. We can use discussions. eg: https://github.com/streamnative/oxia/discussions/new?category=proposal

Yes, i will open an proposal to describe the detail design first.

**Comment by lsytj0413** [comment]
> @lsytj0413 Perhaps we can start with a proposal and design doc for how to implement the change. We can use discussions. eg: https://github.com/streamnative/oxia/discussions/new?category=proposal

Propocal at https://github.com/streamnative/oxia/discussions/412，PTAL

**Comment by lsytj0413** [comment]
Seems this have been implemented at https://github.com/streamnative/oxia/pull/538#event-14438514703
@merlimat  this can be close？
