### ISSUE TITLE
Some Questions about Oxia

### ISSUE THREAD

**Issue by xiaofan-luan** [streamnative/oxia#429]
Hi Team.
Recently I've seen your post and is very impressed about oxia is doing.
Couple of questions about oxia:
1. Is there a plan to replace bookeeper with oxia log storage?
2. If not, will we change bookeeper zk meta to oxia also?
3. What's is typical failure recovery time for one storage node down and Coordinator down?

**Comment by merlimat** [comment]
> 1. Is there a plan to replace bookeeper with oxia log storage?

Not an immediate goal, though it would be something to potentially explore in the future.

> 2. If not, will we change bookeeper zk meta to oxia also?

Yes, BK metadata is already able to use the same interface as Pulsar, thus is able to use Oxia through that.

> 3. What's is typical failure recovery time for one storage node down and Coordinator down?

 - Storage nodes: 
    * Follower: no visible impact on latency (writes are quorum based)
    * Leader: in a normal crash (when the TCP connection is closed), the leader election is triggered immediately. Normally, the latency bump is ~50millis
  
 - Coordinator: there is no dependency for data path on coordinator. If coordinator is down, the storage nodes will continue to work as expected with absolutely no impact. If a storage node crashes at the same time, the leader election will be delayed to when the coordinator is back online.

**Comment by xiaofan-luan** [comment]
> > 1. Is there a plan to replace bookeeper with oxia log storage?
> 
> Not an immediate goal, though it would be something to potentially explore in the future.
> 
> > 2. If not, will we change bookeeper zk meta to oxia also?
> 
> Yes, BK metadata is already able to use the same interface as Pulsar, thus is able to use Oxia through that.
> 
> > 3. What's is typical failure recovery time for one storage node down and Coordinator down?
> 
> * Storage nodes:
>   
>   * Follower: no visible impact on latency (writes are quorum based)
>   * Leader: in a normal crash (when the TCP connection is closed), the leader election is triggered immediately. Normally, the latency bump is ~50millis
> * Coordinator: there is no dependency for data path on coordinator. If coordinator is down, the storage nodes will continue to work as expected with absolutely no impact. If a storage node crashes at the same time, the leader election will be delayed to when the coordinator is back online.

Good to know! thanks for the explanation.
A distributed meta store and log store is very important and oxia + bookie seems to be very promising
